apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: sprint-docker
  name: spring-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: sprint-docker
    spec:
      containers:
      - image: drbhat/sprint-docker
        name: sprint-docker
        ports:
        - name: sprint-docker
          containerPort: 8080 
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: sprint-docker
  name: sprint-docker
spec:
  type: Cluster
  externalTrafficPolicy: local
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: sprint-docker
